"""
THIS IS THE CONFUGURATION FOR STATE REPORT CARD MODULE.
"""

STATE_ID_LIST = [
    "127",
]  # MAHARASHTRA
DISTRICT_ID_LIST = [
    "3705",
    "3718",
    "3720",
    "3725",
    "3732",
    "3708",
]  # AKOLA, JALNA, NASHIK, RATNAGIRI, WARDHA

# STORE IDS IN A TEXT FILE
